---
abstract: 'A non-blocking wrapper around L<Hailo|Hailo>'
author:
  - 'Hinrik Örn Sigurðsson <hinrik.sig@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101612, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Hailo
no_index:
  directory:
    - t
    - xt
    - utils
requires:
  Hailo: 0
  POE: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=POE-Component-Hailo
  homepage: http://search.cpan.org/dist/POE-Component-Hailo/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hinrik/poe-component-hailo.git
version: 0.10
x_authority: cpan:HINRIK
